import jorbagh from '@/assets/images/jorbagh.png'
import civillines from '@/assets/images/civillines.png'

const PROPERTYDETAILS = [
  {
    name: 'Jor Bagh',
    city: 'New Delhi, India',
    sqft: 3500,
    acre: 0.5,
    fractionalInvestment: false,
    registered: 3,
    path: jorbagh,
    id: 1,
    details:
      'This exquisite first-floor apartment is perched on a 515 sqm (617 sq. yds.) plot; the largest plot size of its kind in Jor Bagh, outside the ASI’s limitations and in close proximity to Lodhi Gardens. The apartment faces and has access to a park in the front and the rear providing residents with verdant & serene green views. This recently built 275 sqm (~2,960 sq. ft.) apartment has a beautiful living room with...',
    totalValue: '$ 3,058,654',
    pricePerShare: '$ 15,293',
    bedrooms: 6,
    bath: 4,
    availableSlots: '72',
    fundRaisingEndsIn: '12 days',
  },
  {
    name: 'Penthouse Paradise',
    city: 'New Delhi, India',
    sqft: 5000,
    acre: 0.7,
    fractionalInvestment: true,
    registered: 5,
    path: civillines,
    bedrooms: 6,
    bath: 4,
    id: 2,
    details:
      'This exquisite first-floor apartment is perched on a 515 sqm (617 sq. yds.) plot; the largest plot size of its kind in Jor Bagh, outside the ASI’s limitations and in close proximity to Lodhi Gardens. The apartment faces and has access to a park in the front and the rear providing residents with verdant & serene green views. This recently built 275 sqm (~2,960 sq. ft.) apartment has a beautiful living room with...',
    totalValue: '$ 1,058,654',
    pricePerShare: '$ 11,293',
    availableSlots: '42',
    fundRaisingEndsIn: '10 days',
  },
  {
    name: 'Riverside Mansion',
    city: 'New Delhi, India',
    sqft: 8000,
    acre: 1.2,
    fractionalInvestment: true,
    registered: 10,
    path: jorbagh,
    bedrooms: 6,
    bath: 4,
    id: 3,
    details:
      'This exquisite first-floor apartment is perched on a 515 sqm (617 sq. yds.) plot; the largest plot size of its kind in Jor Bagh, outside the ASI’s limitations and in close proximity to Lodhi Gardens. The apartment faces and has access to a park in the front and the rear providing residents with verdant & serene green views. This recently built 275 sqm (~2,960 sq. ft.) apartment has a beautiful living room with...',
    totalValue: '$ 2,058,654',
    pricePerShare: '$ 21,293',
    availableSlots: '15',
    fundRaisingEndsIn: '11 days',
  },
]
const FEATUREDPROPERTIES: { [key: string]: any } = {
  ongoing: [
    {
      name: 'Sea View Haven',
      city: 'Mumbai, India',
      sqft: 6000,
      acre: 1.0,
      fractionalInvestment: true,
      registered: 80,
      path: jorbagh,
      startingAt: '$2,500,000',
      totalValue: '$9,000,000',
      bedrooms: 6,
      bath: 5,
      id: 4,
      totalRegistration: 100,
      details:
        'This exquisite first-floor apartment is perched on a 515 sqm (617 sq. yds.) plot; the largest plot size of its kind in Jor Bagh, outside the ASI’s limitations and in close proximity to Lodhi Gardens. The apartment faces and has access to a park in the front and the rear providing residents with verdant & serene green views. This recently built 275 sqm (~2,960 sq. ft.) apartment has a beautiful living room with...',
      pricePerShare: '$ 11,293',
      availableSlots: '15',
      fundRaisingEndsIn: '12 days',
    },
    {
      name: 'Heritage Villa',
      city: 'Kolkata, India',
      sqft: 4500,
      acre: 0.8,
      fractionalInvestment: false,
      registered: 6,
      path: civillines,
      startingAt: '$1,800,000',
      totalValue: '$6,500,000',
      bedrooms: 5,
      bath: 4,
      totalRegistration: 20,
      id: 5,
      details:
        'This exquisite first-floor apartment is perched on a 515 sqm (617 sq. yds.) plot; the largest plot size of its kind in Jor Bagh, outside the ASI’s limitations and in close proximity to Lodhi Gardens. The apartment faces and has access to a park in the front and the rear providing residents with verdant & serene green views. This recently built 275 sqm (~2,960 sq. ft.) apartment has a beautiful living room with...',
      pricePerShare: '$ 11,293',
      availableSlots: '15',
      fundRaisingEndsIn: '5 days',
    },
    {
      name: 'Riverside Mansion',
      city: 'New Delhi, India',
      sqft: 8000,
      acre: 1.2,
      fractionalInvestment: true,
      registered: 10,
      path: jorbagh,
      startingAt: '$6,000,000',
      totalValue: '$32,000,000',
      bedrooms: 7,
      bath: 6,
      totalRegistration: 70,
      id: 6,
      details:
        'This exquisite first-floor apartment is perched on a 515 sqm (617 sq. yds.) plot; the largest plot size of its kind in Jor Bagh, outside the ASI’s limitations and in close proximity to Lodhi Gardens. The apartment faces and has access to a park in the front and the rear providing residents with verdant & serene green views. This recently built 275 sqm (~2,960 sq. ft.) apartment has a beautiful living room with...',
      pricePerShare: '$ 21,293',
      availableSlots: '15',
      fundRaisingEndsIn: '7 days',
    },
  ],
  comingsoon: [
    {
      name: 'Ocean View Retreat',
      city: 'Goa, India',
      sqft: 5000,
      acre: 0.9,
      fractionalInvestment: true,
      registered: 0,
      path: civillines,
      startingAt: '$2,000,000',
      totalValue: '$8,000,000',
      bedrooms: 5,
      bath: 4,
      totalRegistration: 80,
      id: 7,
      details:
        'This exquisite first-floor apartment is perched on a 515 sqm (617 sq. yds.) plot; the largest plot size of its kind in Jor Bagh, outside the ASI’s limitations and in close proximity to Lodhi Gardens. The apartment faces and has access to a park in the front and the rear providing residents with verdant & serene green views. This recently built 275 sqm (~2,960 sq. ft.) apartment has a beautiful living room with...',
      pricePerShare: '$ 21,293',
      availableSlots: '15',
      fundRaisingEndsIn: '5 days',
    },
  ],
  closed: [
    {
      name: 'Lakeside Manor',
      city: 'Udaipur, India',
      sqft: 7000,
      acre: 1.5,
      fractionalInvestment: false,
      registered: 30,
      path: civillines,
      startingAt: '$5,500,000',
      totalValue: '$11,000,000',
      bedrooms: 8,
      bath: 7,
      totalRegistration: 30,
      id: 8,
      details:
        'This exquisite firt-floor apartment is perched on a 515 sqm (617 sq. yds.) plot; the largest plot size of its kind in Jor Bagh, outside the ASI’s limitations and in close proximity to Lodhi Gardens. The apartment faces and has access to a park in the front and the rear providing residents with verdant & serene green views. This recently built 275 sqm (~2,960 sq. ft.) apartment has a beautiful living room with...',
      pricePerShare: '$ 11,793',
      availableSlots: '15',
      fundRaisingEndsIn: '8 days',
    },
  ],
}

const KEYMAPPING: { [key: string]: string } = {
  'ongoing bids': 'ongoing',
  'coming soon': 'comingsoon',
  closed: 'closed',
}

export { PROPERTYDETAILS, FEATUREDPROPERTIES, KEYMAPPING }
